apiVersion: v1
kind: Service
metadata:
  name: {{ include "platform-api.fullname" . }}
spec:
  type: ClusterIP
  selector:
    {{- include "platform-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
